### ISSUE TITLE
目标类型无效

### ISSUE THREAD

**Issue by bruce322** [Script-Hub-Org/Script-Hub#1]
转换的最后格式是按照安装的模块来的!
比如：安装了stash的模块，然后从QX转loon，最后的格式仍然是stash！
如果安装的是shadowrocket的模块，然后从QX转stash，最后的格式仍然是shadowrocket的格式。

**Comment by xream** [comment]
WIP

**Comment by chengkongyiban** [comment]
已处理 现在转换结果以target的值为准
