### ISSUE TITLE
求助qx转模块的操作

### ISSUE THREAD

**Issue by windy1lee** [Script-Hub-Org/Script-Hub#10]
https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/ddqd.js
这是脚本地址，多次操作qx转surge模块均未成功。
请问需如何设置？
滴答XX app的

**Comment by xream** [comment]
只能旧版app 我们就不测了 自己研究吧
尝试转换1不行就转换2

windy1lee ***@***.***>于2023年8月20日 周日22:28写道：
