### ISSUE TITLE
希望同平台下的复写转换保持原有参数一致

### ISSUE THREAD

**Issue by shangrenxi** [Script-Hub-Org/Script-Hub#2]
背景：我需要用到script hub的重写排除功能（参数x=artifacts&del=），因此sgmoudle转sgmoudle希望参数不发生变化。
延展：其他相同平台的转换时候可以保持参数不变（简单测了下loon也是多了一些参数，参数值也变化了。）
环境：已安装script hub，转换keywos佬的https://raw.githubusercontent.com/Keywos/rule/main/Sub-Store/Sub-Store.sgmodule

问题点：
1.每条Script的max-suze、timeout参数跟原来的变更了，希望保持一致。
2.每条Script的ability、script-uodate-interval丢失
3.cron内的timeout变更了，希望保持一致。

**Comment by chengkongyiban** [comment]
没有理解你的意思。

**Comment by chengkongyiban** [comment]
已处理 现在surge->surge loon->loon 转换基本原滋原味了
