### ISSUE TITLE
loon插件转surge ios模块失败

### ISSUE THREAD

**Issue by ravy-alt** [Script-Hub-Org/Script-Hub#20]
最近的更新脚本导致部分loon插件转换得到的surge ios模块无法使用：[loon插件地址](https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Plugin/YouTube_remove_ads.plugin?ref_type=heads)
怀疑是由于loon插件中含有以下字段
```
#!system = iOS, iPadOS, macOS
```
而最近的[commit](https://github.com/Script-Hub-Org/Script-Hub/commit/2175582ddc71979e73ee69f7a61b53e16d6dde23)导致转换后的surge模块内容为
```
#!system=mac
```
因此无法在ios使用

**Comment by xream** [comment]
老张之前应该修了
