### ISSUE TITLE
loon 插件转换为 surge 插件时丢失 arg 参数

### ISSUE THREAD

**Issue by oxoxoxox** [Script-Hub-Org/Script-Hub#26]
loon 插件转换为 surge 插件时，loon 插件中定的义Argument字段，转换到 surge 插件后就没了。
例如 https://kelee.one/Tool/Loon/Plugin/NeteaseCloudMusic_remove_ads.plugin

**Comment by xream** [comment]
@oxoxoxox 短期内无计划支持 请使用 高级操作或脚本转换中的"在脚本开头添加代码"

**Comment by oxoxoxox** [comment]
> @oxoxoxox 短期内无计划支持 请使用 高级操作或脚本转换中的"在脚本开头添加代码"

了解，那我去试试你说的这两种方案
