### ISSUE TITLE
Qx重写转换，链接和max-size，结尾➕false

### ISSUE THREAD

**Issue by gys619** [Script-Hub-Org/Script-Hub#4]
![image](https://github.com/Script-Hub-Org/Script-Hub/assets/59304891/6e593b5d-da25-496f-9691-e1f3bf0a9fcc)![image](https://github.com/Script-Hub-Org/Script-Hub/assets/59304891/c7de15c8-aceb-4838-bc0d-6d600f6f4250)![image](https://github.com/Script-Hub-Org/Script-Hub/assets/59304891/1f244a25-5a5e-4b4f-a848-2e7f26bef4e4)
测速链接

https://gist.githubusercontent.com/ddgksf2013/32b3d37d78433a34370cbfb69780160d/raw/glados.js

https://gist.githubusercontent.com/ddgksf2013/f4752e632fd3375ea2811985c5b635dc/raw/alicloud.js

**Comment by chengkongyiban** [comment]
已修正该bug
