### ISSUE TITLE
圈x重写转换surge模块。使用时出现报错信息

### ISSUE THREAD

**Issue by fan0424** [Script-Hub-Org/Script-Hub#5]
如题，使用圈x重写转换surge模块，再使用时，surge的事件里出现红色提示：An exception was catched while evaluate script xxxx(此处为转换的脚本名)：ReferenceError: Can't find variable: setInterval. line number xxx, column: xxxxx

报错的圈x重写例如：
喜马拉雅：https://raw.githubusercontent.com/WeiRen0/Scripts/main/XMVIPTY3.js
芒果tv：https://raw.githubusercontent.com/WeiRen0/Scripts/main/MGTV.js
彩云天气：https://raw.githubusercontent.com/WeiRen0/Scripts/main/cytq.js

**Comment by chengkongyiban** [comment]
你需要尝试勾选"启用脚本转换1"或"启用脚本转换2"

**Comment by fan0424** [comment]
> 你需要尝试勾选"启用脚本转换1"或"启用脚本转换2"

具体怎么使用？只勾选 ”启用脚本转换1/2“下面的 ”全部转换“和”仅进行兼容性转换“么？输入框需要填写东西么？

**Comment by xream** [comment]
一个例子 可在浏览器打开查看我是如何配置的 
 http://script.hub/edit/_start_/https://raw.githubusercontent.com/WeiRen0/Scripts/main/XMVIPTY3.js/_end_/qx_weiren_xmly.sgmodule?jsc=.&n=QX%20%E5%96%9C%E9%A9%AC%E6%8B%89%E9%9B%85%2B%E4%BC%9F%E4%BA%BA&type=qx-rewrite&target=surge-module

**Comment by fan0424** [comment]
> 一个例子 可在浏览器打开查看我是如何配置的 http://script.hub/edit/_start_/https://raw.githubusercontent.com/WeiRen0/Scripts/main/XMVIPTY3.js/_end_/qx_weiren_xmly.sgmodule?jsc=.&n=QX%20%E5%96%9C%E9%A9%AC%E6%8B%89%E9%9B%85%2B%E4%BC%9F%E4%BA%BA&type=qx-rewrite&target=surge-module

刚试了，可以了，感谢大佬
