### ISSUE TITLE
qx重写转surge模块,底部出现部分js代码

### ISSUE THREAD

**Issue by gitupdate** [Script-Hub-Org/Script-Hub#6]
https://raw.githubusercontent.com/id77/QuantumultX/master/Script/jd_hd.js

![image](https://github.com/Script-Hub-Org/Script-Hub/assets/92412374/fe75d471-7c9d-4e13-a17a-b148e72f00cd)

![image](https://github.com/Script-Hub-Org/Script-Hub/assets/92412374/8e410e96-7400-4d3f-8e19-72b3facbd7ba)

**Comment by chengkongyiban** [comment]
已修复该bug，请更新外部资源后重试
