### ISSUE TITLE
请求添加转换为surge模块后 添加平台的功能

### ISSUE THREAD

**Issue by char1eslu** [Script-Hub-Org/Script-Hub#7]
surge的模块可以通过参数system来限制是iOS还是Mac，这样如果是仅为iOS的Mac，在surge Mac的模块将不会显示这个模块，具体使用如下：
#!name=Historical price
#!desc=Display the historical prices of JD and Taobao products.
#!system=ios
[Script]
# > 淘宝比价
。。。
[MITM]

**Comment by xream** [comment]
可以有 但是感觉意义不大
毕竟 你可以在 mac 上不启用这个模块...

**Comment by xream** [comment]
顺便 可以用高级操作实现 ```body = "#!system=ios\n" + body```
<img width="732" alt="image" src="https://github.com/Script-Hub-Org/Script-Hub/assets/1210282/08afe656-d239-4c41-a8a5-610dea741d1e">

**Comment by char1eslu** [comment]
> 顺便 可以用高级操作实现 `body = "#!system=ios\n" + body`
> <img alt="image" width="732" src="https://user-images.githubusercontent.com/1210282/257185606-08afe656-d239-4c41-a8a5-610dea741d1e.png">

好的哈，谢谢
