### ISSUE TITLE
arg参数传递求解

### ISSUE THREAD

**Issue by androidcn** [Script-Hub-Org/Script-Hub#8]
模块https://raw.githubusercontent.com/Keywos/rule/main/module/Barkapps.sgmodule

需要传递key到参数 argument

应该修改哪个位置？
![image](https://github.com/Script-Hub-Org/Script-Hub/assets/271715/96a0794f-2ce4-444b-8726-d221efb237f8)

![image](https://github.com/Script-Hub-Org/Script-Hub/assets/271715/b735e7cf-f81a-4d8c-bd01-c28f88ebb0f7)

参数说明没看懂？求解

arg= 根据关键词锁定脚本配合参数
argv= 修改argument=的值 多关键词用"+"分隔，arg=传入了几项，argv=也必须对应传入几项。 argument中 "+"必须用"t;add;"替代。

**Comment by chengkongyiban** [comment]
arg里 填关键词(比如 Barkapps=type中的Barkapps)

argv里填你需要传递进去的参数

**Comment by androidcn** [comment]
> arg里 填关键词(比如 Barkapps=type中的Barkapps)
> 
> argv里填你需要传递进去的参数

需要自己下载Bark并找到key填进argument

arg 填 argument

argv 填 key
如图

![image](https://github.com/Script-Hub-Org/Script-Hub/assets/271715/afa4567c-d4a3-42e5-bf56-5c1e911dd711)

**Comment by chengkongyiban** [comment]
应该是没有问题的，你试试

**Comment by androidcn** [comment]
> 应该是没有问题的，你试试

源代码是这样的

# 定时获取
Barkapps=type=cron,cronexp="0 10,21 * * *",wake-system=1,timeout=120,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/surgepushBarkapps.js,argument=


arg 写Barkapps=type？
还是 argument 
Argv 写 key的内容？

应该怎么写才对？

**Comment by androidcn** [comment]
> 应该是没有问题的，你试试

源代码是这样的

# 定时获取
Barkapps=type=cron,cronexp="0 10,21 * * *",wake-system=1,timeout=120,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/surgepushBarkapps.js,argument=


arg 写Barkapps=type？
还是 argument 
Argv 写 key的内容？

应该怎么写才对？

**Comment by chengkongyiban** [comment]
你上面那张图的截图是正确操作啊

**Comment by androidcn** [comment]
> 你上面那张图的截图是正确操作啊

argument成功了

问题轮到cron

cronexp="0 10,21 * * *"
加 0 10,15,21 * * *

这个就不成功

![image](https://github.com/Script-Hub-Org/Script-Hub/assets/271715/d6ad1211-cea0-4915-8cda-3d1689966787)

**Comment by chengkongyiban** [comment]
我这里测试是成功的。

**Comment by felixmmy** [comment]
> > 应该是没有问题的，你试试
> 
> 源代码是这样的
> 
> # 定时获取
> Barkapps=type=cron,cronexp="0 10,21 * * *",wake-system=1,timeout=120,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/surgepushBarkapps.js,argument=
> 
> arg 写Barkapps=type？ 还是 argument Argv 写 key的内容？
> 
> 应该怎么写才对？

我把模块直接放本地,在argument=后面填写可以,还是不起作用,这个模块里说持久化uuidkeys是什么意思,没看懂,需要在脚本编辑器里$persistentStore自行添加uuidkeys?

**Comment by felixmmy** [comment]
> > arg里 填关键词(比如 Barkapps=type中的Barkapps)
> > argv里填你需要传递进去的参数
> 
> 需要自己下载Bark并找到key填进argument
> 
> arg 填 argument
> 
> argv 填 key 如图
> 
> ![image](https://private-user-images.githubusercontent.com/271715/258560858-afa4567c-d4a3-42e5-bf56-5c1e911dd711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzg4NjIsIm5iZiI6MTcwNTA3ODU2MiwicGF0aCI6Ii8yNzE3MTUvMjU4NTYwODU4LWFmYTQ1NjdjLWQ0YTMtNDJlNS1iZjU2LTVjMWU5MTFkZDcxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQxNjU2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YThkMzEwYmQxYjUyMjc4M2I4MzY2Y2NjODE5NDM0Njc0NGNlMmJjNmQ2MzI3MjRkZjdmYjAzYTVjNjIyMWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JAXWxtr25fbwb_5oqgLnD2RT9KYfVWhEtthfunNoax4)

我把模块直接放本地,在argument=后面填写key,还是不起作用,这个模块里说持久化uuidkeys是什么意思,没看懂,需要在脚本编辑器里$persistentStore自行添加uuidkeys?

**Comment by felixmmy** [comment]
> > arg里 填关键词(比如 Barkapps=type中的Barkapps)
> > argv里填你需要传递进去的参数
> 
> 需要自己下载Bark并找到key填进argument
> 
> arg 填 argument
> 
> argv 填 key 如图
> 
> ![image](https://private-user-images.githubusercontent.com/271715/258560858-afa4567c-d4a3-42e5-bf56-5c1e911dd711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMDU4MzYsIm5iZiI6MTcwNTEwNTUzNiwicGF0aCI6Ii8yNzE3MTUvMjU4NTYwODU4LWFmYTQ1NjdjLWQ0YTMtNDJlNS1iZjU2LTVjMWU5MTFkZDcxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QwMDI1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTkxNmI5MzdkMzZiMGVmMjI1ZTkyZTc2ODhhOGZkN2VjY2I4ZTBlMjNlNjU3NWZhMTA5ZWVlMWZhOWU5YWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jCxBnHOnyy9vBS5s0nS-PS8OhmKle81ljGAbmYrXoEo)

我就是这样转换的，但是模块没起作用，甚至我把模块下到本地直接添加 argumment=我的 key，也没用，是这个脚本失效了吗
