### ISSUE TITLE
loon转stash，script-providers的名称只有"_x"

### ISSUE THREAD

**Issue by bruce322** [Script-Hub-Org/Script-Hub#9]
loon转stash生成的内容里会是这样：

script-providers:
  "_7":
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Resource/Script/QiDian/QiDian_remove_ads.js
    interval: 86400

**Comment by chengkongyiban** [comment]
请提供原链接。

**Comment by chengkongyiban** [comment]
感谢反馈，已修复
